Add support for libassuan file sockets (WinGnuPG support) (jstarks#6)
albertony/npiperelay pull request #35
Opened 2024-02-27 08:34 UTC by ndimiduk

This PR starts with the work of @NZSmartie and @Lexicality. I've squished the changeset presented on https://github.com/jstarks/npiperelay/pull/6. That commit is then rebased onto `albertony/npiperelay:fork` . Finally, I've used your pre-commit checks and cleaned up the resulting issues.

For context, this change enables `npiperelay` to work with the [assuan protocol ](https://www.gnupg.org/documentation/manuals/assuan/)implemented by GnuPG, thus allowing sockets created by gpg-agent.exe for Windows to be forwarded to and consumed by UNIX processes (i.e., Linux gpg in WSL, remote SSH, docker, &c.).

@albertony please consider adding their work to your maintained `fork`.

2024-03-05 07:53 UTC, albertony requested changes
Thank you.

I will need to take a closer look at this a bit later, but for now I have commented on this one thing. The original PR contains quite old commits, from 2017 to 2019, so I want to make sure the code is on par with latest version of go etc.

2024-03-05 07:53 UTC, albertony commented on npiperelay.go
> +}
I removed this function in my fork (https://github.com/albertony/npiperelay/commit/6ec21f6d7efbe654aa21d2618860984697981833), so it shouldn't be reintroduced.

2024-03-05 07:53 UTC, albertony commented on npiperelay.go
> +	if underlyingError(err) == windows.ERROR_BROKEN_PIPE || underlyingError(err) == windows.ERROR_PIPE_NOT_CONNECTED {
As mentioned, the function is not needed, so this line does not need to be changed.

2024-09-11 22:35 UTC, lucasfcnunes commented
@ndimiduk PING

2025-02-05 14:44 UTC, albertony commented
Closing stale PR in favor of https://github.com/albertony/npiperelay/pull/52

2025-02-05 14:44 UTC, closed without merging